const $ = (s, p=document) => p.querySelector(s);
const $$ = (s, p=document) => [...p.querySelectorAll(s)];
let favourites = JSON.parse(localStorage.getItem('pll-favourites') || '[]');
let quizIndex = 0, quizScore = 0, activeQuiz = [];

function escapeHTML(value){return String(value).replace(/[&<>"']/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function topicCard(t){const saved=favourites.includes(t.id);return `<article class="article-card"><span class="meta">${t.bahagian} · ${t.article}</span><h3>${t.title}</h3><p>${t.easy}</p><div class="tag-list">${t.keywords.slice(0,3).map(k=>`<span class="tag">${k}</span>`).join('')}</div><div class="card-actions"><button class="open-topic" data-open="${t.id}">Buka topik →</button><button class="fav-button" data-fav="${t.id}" aria-label="${saved?'Buang daripada':'Simpan ke'} kegemaran">${saved?'★':'☆'}</button></div></article>`}
function bindCards(scope=document){$$('[data-open]',scope).forEach(b=>b.addEventListener('click',()=>openTopic(b.dataset.open)));$$('[data-fav]',scope).forEach(b=>b.addEventListener('click',()=>toggleFav(b.dataset.fav)));}
function updateFavs(){localStorage.setItem('pll-favourites',JSON.stringify(favourites));$('#favCount').textContent=favourites.length;const list=TOPICS.filter(t=>favourites.includes(t.id));$('#favouritesGrid').innerHTML=list.length?list.map(topicCard).join(''):'<p class="empty-state">Belum ada topik disimpan. Tekan ☆ pada mana-mana topik untuk menyimpannya.</p>';bindCards($('#favouritesGrid'));}
function toggleFav(id){favourites=favourites.includes(id)?favourites.filter(x=>x!==id):[...favourites,id];updateFavs();const visible=$('#resultsGrid').innerHTML;if(visible) runSearch($('#searchInput').value);}
function score(t,q){const hay=[t.category,t.bahagian,t.article,t.title,...t.keywords,...t.alt,t.core,t.easy,...t.details,t.note,t.source].join(' ').toLocaleLowerCase('ms');const parts=q.toLocaleLowerCase('ms').split(/\s+/).filter(Boolean);return parts.reduce((n,p)=>n+(hay.includes(p)?1:0),0)+(t.article.toLowerCase()===q.toLowerCase()?8:0)+(t.title.toLowerCase().includes(q.toLowerCase())?4:0);}
function runSearch(q){q=q.trim();const section=$('#hasil');if(!q){section.hidden=true;return}const found=TOPICS.map(t=>({t,s:score(t,q)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).map(x=>x.t);section.hidden=false;$('#resultsTitle').textContent=`Hasil untuk “${q}”`;$('#resultsGrid').innerHTML=found.length?found.map(topicCard).join(''):`<p class="empty-state">Tiada hasil dijumpai. Cuba kata kunci lain seperti “pendidikan”, “maksud” atau “pindaan”.</p>`;bindCards($('#resultsGrid'));section.scrollIntoView({behavior:'smooth',block:'start'});}
function openTopic(id){const t=TOPICS.find(x=>x.id===id);if(!t)return;const el=$('#topik');el.hidden=false;el.innerHTML=`<div class="topic-header"><p class="eyebrow">${t.bahagian.toUpperCase()} · ${t.category.toUpperCase()}</p><h2>${t.article}: ${t.title}</h2><p class="topic-sub">Huraian pembelajaran berikut membantu pemahaman. Ia bukan teks perundangan.</p></div><div class="topic-layout"><div><article class="learn-block"><h3>IDEA UTAMA</h3><p>${t.core}</p></article><article class="learn-block easy"><h3>PENERANGAN MUDAH</h3><p>${t.easy}</p></article><article class="learn-block"><h3>PERKARA PENTING</h3><ul>${t.details.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="learn-block note"><h3>NOTA CEPAT</h3><p>${t.note}</p></article><details class="source-block"><summary>TEKS ASAL · buka petikan sumber</summary><p>${t.source}</p><small>Petikan dirujuk daripada Perlembagaan Persekutuan, Cetakan Semula 2020. Rujuk dokumen penuh untuk teks lengkap.</small></details></div><aside><div class="side-card"><h3>KATA KUNCI</h3><div class="tag-list">${[...t.keywords,...t.alt].map(k=>`<span class="tag">${k}</span>`).join('')}</div></div><div class="side-card"><h3>FOKUS BELAJAR</h3><p>${t.focus}</p></div><div class="side-card"><h3>PERINGATAN</h3><p>Gunakan penerangan mudah untuk belajar. Untuk maksud perundangan tepat, baca teks asal penuh.</p></div><button class="open-topic" data-fav="${t.id}">${favourites.includes(t.id)?'★ Disimpan':'☆ Simpan topik'}</button></aside></div>`;bindCards(el);el.scrollIntoView({behavior:'smooth',block:'start'});}
function renderLibrary(){const grid=$('#libraryGrid');grid.innerHTML=LIBRARY.map(([n,name,desc,links])=>`<button class="library-card" data-library="${name}"><span class="library-number">${n}</span><h3>${name}</h3><p>${desc}</p><small>${links.join(' · ')}</small></button>`).join('');$$('[data-library]',grid).forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.library;const matching=TOPICS.filter(t=>t.category===name || (name==='Asas Perlembagaan'&&['Perkara 4','Perkara 159','Perkara 160'].includes(t.article)));if(matching.length){$('#hasil').hidden=false;$('#resultsTitle').textContent=name;$('#resultsGrid').innerHTML=matching.map(topicCard).join('');bindCards($('#resultsGrid'));$('#hasil').scrollIntoView({behavior:'smooth',block:'start'});}else{runSearch(name);}}));}
function renderRevision(){const choices=$('#revisionChoices');choices.innerHTML=TOPICS.map(t=>`<button data-revise="${t.id}">${t.article}</button>`).join('');$$('[data-revise]',choices).forEach(b=>b.addEventListener('click',()=>{const t=TOPICS.find(x=>x.id===b.dataset.revise);$$('[data-revise]').forEach(x=>x.classList.toggle('active',x===b));$('#revisionCard').innerHTML=`<p class="eyebrow">${t.article.toUpperCase()} · ${t.category.toUpperCase()}</p><h3>${t.title}</h3><p>${t.core}</p><ul>${t.details.slice(0,3).map(x=>`<li>${x}</li>`).join('')}</ul><div class="tag-list">${t.keywords.map(k=>`<span class="tag">${k}</span>`).join('')}</div><button class="next-button" data-open="${t.id}">Baca topik penuh</button>`;bindCards($('#revisionCard'));}));}
function setupQuiz(){const cats=['Semua topik',...new Set(QUIZZES.map(q=>q.category))];$('#quizCategory').innerHTML=cats.map(x=>`<option>${x}</option>`).join('');$('#quizCategory').addEventListener('change',startQuiz);startQuiz();}
function startQuiz(){const cat=$('#quizCategory').value;activeQuiz=QUIZZES.filter(q=>cat==='Semua topik'||q.category===cat);quizIndex=0;quizScore=0;renderQuestion();}
function renderQuestion(){const box=$('#quizBox');if(!activeQuiz.length){box.textContent='Tiada soalan untuk kategori ini.';return}if(quizIndex>=activeQuiz.length){box.innerHTML=`<p class="eyebrow">SELESAI</p><p class="quiz-question">Skor anda: ${quizScore} / ${activeQuiz.length}</p><p>Teruskan belajar dengan membuka topik atau cuba kuiz sekali lagi.</p><button class="next-button" id="retryQuiz">Cuba lagi</button>`;$('#retryQuiz').onclick=startQuiz;return}const q=activeQuiz[quizIndex];box.innerHTML=`<div class="quiz-progress">SOALAN ${quizIndex+1} DARIPADA ${activeQuiz.length} · SKOR ${quizScore}</div><p class="quiz-question">${q.question}</p><div class="answers">${q.options.map((o,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>`;$$('[data-answer]',box).forEach(b=>b.onclick=()=>answerQuestion(Number(b.dataset.answer)));}
function answerQuestion(answer){const q=activeQuiz[quizIndex],correct=answer===q.answer;$$('.answer',$('#quizBox')).forEach(b=>{b.disabled=true;const a=Number(b.dataset.answer);b.classList.toggle('correct',a===q.answer);b.classList.toggle('wrong',a===answer&&!correct)});if(correct)quizScore++;$('#quizBox').insertAdjacentHTML('beforeend',`<div class="quiz-feedback"><strong>${correct?'Betul':'Belum tepat'}.</strong> ${q.explanation}</div><button class="next-button" id="nextQuiz">${quizIndex+1===activeQuiz.length?'Lihat skor':'Soalan seterusnya'}</button>`);$('#nextQuiz').onclick=()=>{quizIndex++;renderQuestion();};}
$('#searchButton').addEventListener('click',()=>runSearch($('#searchInput').value));$('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch(e.currentTarget.value)});$$('[data-query]').forEach(b=>b.addEventListener('click',()=>{$('#searchInput').value=b.dataset.query;runSearch(b.dataset.query)}));$('#clearSearch').onclick=()=>{$('#searchInput').value='';$('#hasil').hidden=true};$('#menuButton').onclick=()=>{const n=$('#mainNav');n.classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',n.classList.contains('open'));};$$('nav a').forEach(a=>a.addEventListener('click',()=>$('#mainNav').classList.remove('open')));renderLibrary();renderRevision();updateFavs();setupQuiz();
